version: "3.8"

services:
  mysql:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: addresses_db
    volumes:
      - db-data:/var/lib/mysql
      - ./api/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

  api:
    build: ./api
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: addresses_db
      DB_USER: root
      DB_PASS: root
    networks:
      - app-network

  front_admin:
    build: ./front_admin
    restart: always
    networks:
      - app-network

  front_users:
    build: ./front_users
    restart: always
    networks:
      - app-network

  reverse-proxy:
    image: nginx:1.25.3-alpine
    volumes:
      - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - front_admin
      - front_users
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: